#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

foamCleanTutorials cases

# pre-processing
runApplication blockMesh

#i=1
#while [ "$i" -le 3 ]; do
#    rm log.refineMesh >/dev/null 2>&1
#    runApplication refineMesh
#    i=$((i + 1))
#done
for s in 3 2.5 2; do
    rm log.refineMesh >/dev/null 2>&1
    foamDictionary system/refineMeshDict -entry zones/powderBed/scale -set "$s"
    runApplication refineMesh
done
runApplication checkMesh

runApplication setFields

runApplication decomposePar
foamPostProcess -func "layerHeight" -latestTime > log.layerHeight
runApplication reconstructPar

. $WM_PROJECT_USER_DIR/.venv/bin/activate
python3 surf.py
deactivate

#------------------------------------------------------------------------------